-- Generated from https://wilayah.id/api/provinces.json and https://wilayah.id/api/regencies/{provinceCode}.json on 2026-06-03.

WITH indonesia AS (
  SELECT id FROM countries WHERE code = 'ID' LIMIT 1
),
province_lookup AS (
  SELECT p.id, p.code, p.country_id
  FROM provinces p
  JOIN indonesia i ON i.id = p.country_id
),
legacy_city_seed(province_code, city_name) AS (
  VALUES
  ('11', 'Banda Aceh'),
  ('12', 'Medan'),
  ('13', 'Padang'),
  ('14', 'Pekanbaru'),
  ('15', 'Jambi'),
  ('16', 'Palembang'),
  ('17', 'Bengkulu'),
  ('18', 'Bandar Lampung'),
  ('19', 'Pangkalpinang'),
  ('21', 'Tanjung Pinang'),
  ('31', 'Jakarta'),
  ('32', 'Bandung'),
  ('33', 'Semarang'),
  ('34', 'Yogyakarta'),
  ('35', 'Surabaya'),
  ('36', 'Serang'),
  ('51', 'Denpasar'),
  ('52', 'Mataram'),
  ('53', 'Kupang'),
  ('61', 'Pontianak'),
  ('62', 'Palangka Raya'),
  ('63', 'Banjarbaru'),
  ('64', 'Samarinda'),
  ('65', 'Tanjung Selor'),
  ('71', 'Manado'),
  ('72', 'Palu'),
  ('73', 'Makassar'),
  ('74', 'Kendari'),
  ('75', 'Gorontalo'),
  ('76', 'Mamuju'),
  ('81', 'Ambon'),
  ('82', 'Sofifi'),
  ('91', 'Jayapura'),
  ('92', 'Manokwari'),
  ('93', 'Merauke'),
  ('94', 'Nabire'),
  ('95', 'Wamena'),
  ('96', 'Sorong')
)
DELETE FROM cities c
USING province_lookup p, legacy_city_seed s
WHERE c.country_id = p.country_id
  AND c.province_id = p.id
  AND p.code = s.province_code
  AND c.name = s.city_name
  AND NOT EXISTS (SELECT 1 FROM venues v WHERE v.city_id = c.id)
  AND NOT EXISTS (SELECT 1 FROM talents t WHERE t.city_id = c.id);

WITH indonesia AS (
  SELECT id FROM countries WHERE code = 'ID' LIMIT 1
),
province_lookup AS (
  SELECT p.id, p.code, p.country_id
  FROM provinces p
  JOIN indonesia i ON i.id = p.country_id
),
city_seed(province_code, city_name, latitude, longitude) AS (
  VALUES
  ('11', 'Kabupaten Aceh Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kabupaten Aceh Tenggara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kabupaten Aceh Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kabupaten Aceh Tengah', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kabupaten Aceh Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kabupaten Aceh Besar', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kabupaten Pidie', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kabupaten Aceh Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kabupaten Simeulue', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kabupaten Aceh Singkil', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kabupaten Bireuen', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kabupaten Aceh Barat Daya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kabupaten Gayo Lues', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kabupaten Aceh Jaya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kabupaten Nagan Raya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kabupaten Aceh Tamiang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kabupaten Bener Meriah', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kabupaten Pidie Jaya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kota Banda Aceh', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kota Sabang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kota Lhokseumawe', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kota Langsa', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('11', 'Kota Subulussalam', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Tapanuli Tengah', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Tapanuli Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Tapanuli Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Nias', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Langkat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Karo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Deli Serdang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Simalungun', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Asahan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Labuhanbatu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Dairi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Toba', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Mandailing Natal', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Nias Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Pakpak Bharat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Humbang Hasundutan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Samosir', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Serdang Bedagai', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Batu Bara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Padang Lawas Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Padang Lawas', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Labuhanbatu Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Labuhanbatu Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Nias Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kabupaten Nias Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kota Medan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kota Pematangsiantar', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kota Sibolga', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kota Tanjungbalai', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kota Binjai', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kota Tebing Tinggi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kota Padangsidimpuan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('12', 'Kota Gunungsitoli', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kabupaten Pesisir Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kabupaten Solok', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kabupaten Sijunjung', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kabupaten Tanah Datar', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kabupaten Padang Pariaman', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kabupaten Agam', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kabupaten Lima Puluh Kota', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kabupaten Pasaman', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kabupaten Kepulauan Mentawai', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kabupaten Dharmasraya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kabupaten Solok Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kabupaten Pasaman Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kota Padang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kota Solok', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kota Sawahlunto', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kota Padang Panjang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kota Bukittinggi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kota Payakumbuh', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('13', 'Kota Pariaman', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('14', 'Kabupaten Kampar', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('14', 'Kabupaten Indragiri Hulu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('14', 'Kabupaten Bengkalis', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('14', 'Kabupaten Indragiri Hilir', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('14', 'Kabupaten Pelalawan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('14', 'Kabupaten Rokan Hulu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('14', 'Kabupaten Rokan Hilir', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('14', 'Kabupaten Siak', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('14', 'Kabupaten Kuantan Singingi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('14', 'Kabupaten Kepulauan Meranti', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('14', 'Kota Pekanbaru', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('14', 'Kota Dumai', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('15', 'Kabupaten Kerinci', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('15', 'Kabupaten Merangin', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('15', 'Kabupaten Sarolangun', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('15', 'Kabupaten Batanghari', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('15', 'Kabupaten Muaro Jambi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('15', 'Kabupaten Tanjung Jabung Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('15', 'Kabupaten Tanjung Jabung Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('15', 'Kabupaten Bungo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('15', 'Kabupaten Tebo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('15', 'Kota Jambi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('15', 'Kota Sungai Penuh', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('16', 'Kabupaten Ogan Komering Ulu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('16', 'Kabupaten Ogan Komering Ilir', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('16', 'Kabupaten Muara Enim', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('16', 'Kabupaten Lahat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('16', 'Kabupaten Musi Rawas', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('16', 'Kabupaten Musi Banyuasin', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('16', 'Kabupaten Banyuasin', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('16', 'Kabupaten Ogan Komering Ulu Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('16', 'Kabupaten Ogan Komering Ulu Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('16', 'Kabupaten Ogan Ilir', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('16', 'Kabupaten Empat Lawang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('16', 'Kabupaten Penukal Abab Lematang Ilir', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('16', 'Kabupaten Musi Rawas Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('16', 'Kota Palembang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('16', 'Kota Pagar Alam', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('16', 'Kota Lubuk Linggau', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('16', 'Kota Prabumulih', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('17', 'Kabupaten Bengkulu Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('17', 'Kabupaten Rejang Lebong', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('17', 'Kabupaten Bengkulu Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('17', 'Kabupaten Kaur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('17', 'Kabupaten Seluma', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('17', 'Kabupaten Mukomuko', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('17', 'Kabupaten Lebong', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('17', 'Kabupaten Kepahiang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('17', 'Kabupaten Bengkulu Tengah', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('17', 'Kota Bengkulu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('18', 'Kabupaten Lampung Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('18', 'Kabupaten Lampung Tengah', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('18', 'Kabupaten Lampung Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('18', 'Kabupaten Lampung Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('18', 'Kabupaten Tulang Bawang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('18', 'Kabupaten Tanggamus', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('18', 'Kabupaten Lampung Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('18', 'Kabupaten Way Kanan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('18', 'Kabupaten Pesawaran', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('18', 'Kabupaten Pringsewu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('18', 'Kabupaten Mesuji', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('18', 'Kabupaten Tulang Bawang Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('18', 'Kabupaten Pesisir Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('18', 'Kota Bandar Lampung', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('18', 'Kota Metro', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('19', 'Kabupaten Bangka', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('19', 'Kabupaten Belitung', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('19', 'Kabupaten Bangka Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('19', 'Kabupaten Bangka Tengah', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('19', 'Kabupaten Bangka Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('19', 'Kabupaten Belitung Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('19', 'Kota Pangkal Pinang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('21', 'Kabupaten Bintan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('21', 'Kabupaten Karimun', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('21', 'Kabupaten Natuna', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('21', 'Kabupaten Lingga', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('21', 'Kabupaten Kepulauan Anambas', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('21', 'Kota Batam', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('21', 'Kota Tanjung Pinang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('31', 'Kabupaten Administrasi Kepulauan Seribu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('31', 'Kota Administrasi Jakarta Pusat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('31', 'Kota Administrasi Jakarta Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('31', 'Kota Administrasi Jakarta Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('31', 'Kota Administrasi Jakarta Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('31', 'Kota Administrasi Jakarta Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Bogor', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Sukabumi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Cianjur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Bandung', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Garut', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Tasikmalaya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Ciamis', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Kuningan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Cirebon', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Majalengka', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Sumedang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Indramayu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Subang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Purwakarta', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Karawang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Bekasi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Bandung Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kabupaten Pangandaran', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kota Bogor', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kota Sukabumi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kota Bandung', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kota Cirebon', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kota Bekasi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kota Depok', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kota Cimahi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kota Tasikmalaya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('32', 'Kota Banjar', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Cilacap', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Banyumas', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Purbalingga', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Banjarnegara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Kebumen', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Purworejo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Wonosobo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Magelang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Boyolali', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Klaten', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Sukoharjo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Wonogiri', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Karanganyar', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Sragen', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Grobogan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Blora', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Rembang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Pati', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Kudus', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Jepara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Demak', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Semarang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Temanggung', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Kendal', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Batang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Pekalongan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Pemalang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Tegal', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kabupaten Brebes', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kota Magelang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kota Surakarta', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kota Salatiga', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kota Semarang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kota Pekalongan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('33', 'Kota Tegal', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('34', 'Kabupaten Kulon Progo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('34', 'Kabupaten Bantul', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('34', 'Kabupaten Gunungkidul', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('34', 'Kabupaten Sleman', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('34', 'Kota Yogyakarta', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Pacitan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Ponorogo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Trenggalek', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Tulungagung', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Blitar', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Kediri', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Malang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Lumajang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Jember', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Banyuwangi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Bondowoso', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Situbondo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Probolinggo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Pasuruan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Sidoarjo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Mojokerto', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Jombang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Nganjuk', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Madiun', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Magetan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Ngawi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Bojonegoro', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Tuban', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Lamongan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Gresik', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Bangkalan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Sampang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Pamekasan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kabupaten Sumenep', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kota Kediri', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kota Blitar', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kota Malang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kota Probolinggo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kota Pasuruan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kota Mojokerto', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kota Madiun', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kota Surabaya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('35', 'Kota Batu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('36', 'Kabupaten Pandeglang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('36', 'Kabupaten Lebak', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('36', 'Kabupaten Tangerang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('36', 'Kabupaten Serang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('36', 'Kota Tangerang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('36', 'Kota Cilegon', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('36', 'Kota Serang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('36', 'Kota Tangerang Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('51', 'Kabupaten Jembrana', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('51', 'Kabupaten Tabanan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('51', 'Kabupaten Badung', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('51', 'Kabupaten Gianyar', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('51', 'Kabupaten Klungkung', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('51', 'Kabupaten Bangli', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('51', 'Kabupaten Karangasem', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('51', 'Kabupaten Buleleng', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('51', 'Kota Denpasar', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('52', 'Kabupaten Lombok Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('52', 'Kabupaten Lombok Tengah', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('52', 'Kabupaten Lombok Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('52', 'Kabupaten Sumbawa', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('52', 'Kabupaten Dompu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('52', 'Kabupaten Bima', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('52', 'Kabupaten Sumbawa Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('52', 'Kabupaten Lombok Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('52', 'Kota Mataram', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('52', 'Kota Bima', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Kupang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Timor Tengah Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Timor Tengah Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Belu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Alor', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Flores Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Sikka', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Ende', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Ngada', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Manggarai', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Sumba Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Sumba Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Lembata', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Rote Ndao', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Manggarai Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Nagekeo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Sumba Tengah', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Sumba Barat Daya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Manggarai Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Sabu Raijua', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kabupaten Malaka', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('53', 'Kota Kupang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('61', 'Kabupaten Sambas', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('61', 'Kabupaten Mempawah', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('61', 'Kabupaten Sanggau', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('61', 'Kabupaten Ketapang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('61', 'Kabupaten Sintang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('61', 'Kabupaten Kapuas Hulu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('61', 'Kabupaten Bengkayang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('61', 'Kabupaten Landak', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('61', 'Kabupaten Sekadau', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('61', 'Kabupaten Melawi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('61', 'Kabupaten Kayong Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('61', 'Kabupaten Kubu Raya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('61', 'Kota Pontianak', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('61', 'Kota Singkawang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('62', 'Kabupaten Kotawaringin Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('62', 'Kabupaten Kotawaringin Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('62', 'Kabupaten Kapuas', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('62', 'Kabupaten Barito Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('62', 'Kabupaten Barito Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('62', 'Kabupaten Katingan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('62', 'Kabupaten Seruyan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('62', 'Kabupaten Sukamara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('62', 'Kabupaten Lamandau', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('62', 'Kabupaten Gunung Mas', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('62', 'Kabupaten Pulang Pisau', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('62', 'Kabupaten Murung Raya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('62', 'Kabupaten Barito Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('62', 'Kota Palangkaraya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('63', 'Kabupaten Tanah Laut', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('63', 'Kabupaten Kotabaru', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('63', 'Kabupaten Banjar', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('63', 'Kabupaten Barito Kuala', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('63', 'Kabupaten Tapin', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('63', 'Kabupaten Hulu Sungai Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('63', 'Kabupaten Hulu Sungai Tengah', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('63', 'Kabupaten Hulu Sungai Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('63', 'Kabupaten Tabalong', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('63', 'Kabupaten Tanah Bumbu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('63', 'Kabupaten Balangan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('63', 'Kota Banjarmasin', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('63', 'Kota Banjarbaru', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('64', 'Kabupaten Paser', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('64', 'Kabupaten Kutai Kartanegara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('64', 'Kabupaten Berau', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('64', 'Kabupaten Kutai Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('64', 'Kabupaten Kutai Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('64', 'Kabupaten Penajam Paser Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('64', 'Kabupaten Mahakam Ulu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('64', 'Kota Balikpapan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('64', 'Kota Samarinda', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('64', 'Kota Bontang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('65', 'Kabupaten Bulungan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('65', 'Kabupaten Malinau', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('65', 'Kabupaten Nunukan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('65', 'Kabupaten Tana Tidung', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('65', 'Kota Tarakan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('71', 'Kabupaten Bolaang Mongondow', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('71', 'Kabupaten Minahasa', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('71', 'Kabupaten Kepulauan Sangihe', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('71', 'Kabupaten Kepulauan Talaud', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('71', 'Kabupaten Minahasa Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('71', 'Kabupaten Minahasa Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('71', 'Kabupaten Minahasa Tenggara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('71', 'Kabupaten Bolaang Mongondow Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('71', 'Kabupaten Kep. Siau Tagulandang Biaro', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('71', 'Kabupaten Bolaang Mongondow Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('71', 'Kabupaten Bolaang Mongondow Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('71', 'Kota Manado', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('71', 'Kota Bitung', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('71', 'Kota Tomohon', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('71', 'Kota Kotamobagu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('72', 'Kabupaten Banggai', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('72', 'Kabupaten Poso', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('72', 'Kabupaten Donggala', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('72', 'Kabupaten Toli-Toli', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('72', 'Kabupaten Buol', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('72', 'Kabupaten Morowali', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('72', 'Kabupaten Banggai Kepulauan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('72', 'Kabupaten Parigi Moutong', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('72', 'Kabupaten Tojo Una Una', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('72', 'Kabupaten Sigi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('72', 'Kabupaten Banggai Laut', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('72', 'Kabupaten Morowali Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('72', 'Kota Palu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Kepulauan Selayar', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Bulukumba', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Bantaeng', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Jeneponto', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Takalar', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Gowa', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Sinjai', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Bone', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Maros', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Pangkajene dan Kepulauan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Barru', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Soppeng', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Wajo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Sidenreng Rappang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Pinrang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Enrekang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Luwu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Tana Toraja', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Luwu Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Luwu Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kabupaten Toraja Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kota Makassar', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kota Parepare', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('73', 'Kota Palopo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('74', 'Kabupaten Kolaka', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('74', 'Kabupaten Konawe', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('74', 'Kabupaten Muna', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('74', 'Kabupaten Buton', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('74', 'Kabupaten Konawe Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('74', 'Kabupaten Bombana', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('74', 'Kabupaten Wakatobi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('74', 'Kabupaten Kolaka Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('74', 'Kabupaten Konawe Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('74', 'Kabupaten Buton Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('74', 'Kabupaten Kolaka Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('74', 'Kabupaten Konawe Kepulauan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('74', 'Kabupaten Muna Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('74', 'Kabupaten Buton Tengah', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('74', 'Kabupaten Buton Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('74', 'Kota Kendari', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('74', 'Kota Bau Bau', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('75', 'Kabupaten Gorontalo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('75', 'Kabupaten Boalemo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('75', 'Kabupaten Bone Bolango', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('75', 'Kabupaten Pohuwato', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('75', 'Kabupaten Gorontalo Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('75', 'Kota Gorontalo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('76', 'Kabupaten Pasangkayu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('76', 'Kabupaten Mamuju', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('76', 'Kabupaten Mamasa', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('76', 'Kabupaten Polewali Mandar', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('76', 'Kabupaten Majene', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('76', 'Kabupaten Mamuju Tengah', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('81', 'Kabupaten Maluku Tengah', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('81', 'Kabupaten Maluku Tenggara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('81', 'Kabupaten Kepulauan Tanimbar', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('81', 'Kabupaten Buru', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('81', 'Kabupaten Seram Bagian Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('81', 'Kabupaten Seram Bagian Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('81', 'Kabupaten Kepulauan Aru', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('81', 'Kabupaten Maluku Barat Daya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('81', 'Kabupaten Buru Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('81', 'Kota Ambon', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('81', 'Kota Tual', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('82', 'Kabupaten Halmahera Barat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('82', 'Kabupaten Halmahera Tengah', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('82', 'Kabupaten Halmahera Utara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('82', 'Kabupaten Halmahera Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('82', 'Kabupaten Kepulauan Sula', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('82', 'Kabupaten Halmahera Timur', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('82', 'Kabupaten Pulau Morotai', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('82', 'Kabupaten Pulau Taliabu', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('82', 'Kota Ternate', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('82', 'Kota Tidore Kepulauan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('91', 'Kabupaten Jayapura', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('91', 'Kabupaten Kepulauan Yapen', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('91', 'Kabupaten Biak Numfor', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('91', 'Kabupaten Sarmi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('91', 'Kabupaten Keerom', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('91', 'Kabupaten Waropen', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('91', 'Kabupaten Supiori', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('91', 'Kabupaten Mamberamo Raya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('91', 'Kota Jayapura', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('92', 'Kabupaten Manokwari', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('92', 'Kabupaten Fak Fak', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('92', 'Kabupaten Teluk Bintuni', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('92', 'Kabupaten Teluk Wondama', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('92', 'Kabupaten Kaimana', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('92', 'Kabupaten Manokwari Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('92', 'Kabupaten Pegunungan Arfak', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('93', 'Kabupaten Merauke', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('93', 'Kabupaten Boven Digoel', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('93', 'Kabupaten Mappi', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('93', 'Kabupaten Asmat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('94', 'Kabupaten Nabire', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('94', 'Kabupaten Puncak Jaya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('94', 'Kabupaten Paniai', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('94', 'Kabupaten Mimika', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('94', 'Kabupaten Puncak', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('94', 'Kabupaten Dogiyai', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('94', 'Kabupaten Intan Jaya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('94', 'Kabupaten Deiyai', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('95', 'Kabupaten Jayawijaya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('95', 'Kabupaten Pegunungan Bintang', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('95', 'Kabupaten Yahukimo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('95', 'Kabupaten Tolikara', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('95', 'Kabupaten Mamberamo Tengah', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('95', 'Kabupaten Yalimo', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('95', 'Kabupaten Lanny Jaya', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('95', 'Kabupaten Nduga', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('96', 'Kabupaten Sorong', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('96', 'Kabupaten Sorong Selatan', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('96', 'Kabupaten Raja Ampat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('96', 'Kabupaten Tambrauw', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('96', 'Kabupaten Maybrat', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6))),
  ('96', 'Kota Sorong', CAST(NULL AS DECIMAL(10,6)), CAST(NULL AS DECIMAL(10,6)))
)
INSERT INTO cities (name, country_id, province_id, latitude, longitude, created_at, updated_at)
SELECT
  city_seed.city_name,
  province_lookup.country_id,
  province_lookup.id,
  city_seed.latitude,
  city_seed.longitude,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
FROM city_seed
JOIN province_lookup ON province_lookup.code = city_seed.province_code
ON CONFLICT (name, country_id) DO UPDATE
SET province_id = EXCLUDED.province_id,
    latitude = COALESCE(EXCLUDED.latitude, cities.latitude),
    longitude = COALESCE(EXCLUDED.longitude, cities.longitude),
    updated_at = CURRENT_TIMESTAMP;
